apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-client
  namespace: spring-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-client
  template:
    metadata:
      labels:
        app: spring-client
    spec:
      serviceAccountName: spring-dev-account
      containers:
        - name: spring-client
          image: ecr-addr/ecr-name:image-name
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: TZ
              value: Asia/Seoul
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1